spring:
  application:
    name: account
  datasource:
    url: jdbc:h2:mem:devDb
  h2:
    console:
      enabled: true
      path: /h2-console
  config:
    import: "optional:configserver:http://localhost:9999"
server:
  port: 8081